import type { Metadata } from "next";
import { Suspense } from "react";
import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "@mui/material";
import { theme } from "./themes/theme";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import CssBaseline from "@mui/material/CssBaseline";
import Navbar from "@/app/components/Navbar";
import StarsBackground from '@/app/components/StarsBackground';
import { Box, Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StarsBackground />
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Navbar />
          <ToastContainer />
          <Box
            component="div"
            display="flex"
            justifyContent="center"
            my={14}
            mx={{ xs: 2, sm: 16 }}
          >
            <Box
              component="div"
              width="100%"
              maxWidth={1400}
              display="flex"
              justifyContent={"center"}
            >
              <Suspense
                fallback={<Typography color="#fff">Loading...</Typography>}
              >
                {children}
              </Suspense>
            </Box>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
