import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "@mui/material";
import { theme } from "./themes/theme";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import CssBaseline from "@mui/material/CssBaseline";
import Navbar from "@/app/components/Navbar";
import PageTransition from "@/app/components/PageTransition";
import StairTransition from "@/app/components/StairTransition";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

// const jetbrainsMono = JetBrains_Mono({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
//   variable: '--font-jetbrainsMono'
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Navbar />
          <ToastContainer />
          <StairTransition />
          <PageTransition>
            <Box
              display="flex"
              justifyContent="center"
              my={6}
              mx={{ xs: 6, sm: 16 }}
            >
              <Box width="100%" maxWidth={1000}>
                {children}
              </Box>
            </Box>
          </PageTransition>
        </ThemeProvider>
      </body>
    </html>
  );
}
